---
dependency:
  name: galaxy
  options:
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/requirements.yml"
driver:
  name: default
platforms:
  - name: dvwa-ubuntu-2404
    groups:
      - dvwa
provisioner:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
