---
- name: Deletes anonymous MySQL server user for localhost
  mysql_user: user="" state=absent login_password={{ mysql_root_password }} login_user=root

- name: Secures the MySQL root user
  mysql_user: user="root" password="{{ mysql_root_password }}" host="{{ item }}" login_password="{{mysql_root_password}}" login_user=root

  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"

- name: Removes the MySQL test database
  mysql_db: db=test state=absent login_password="{{ mysql_root_password }}" login_user=root

- name: creating new user
  mysql_user: user=dvwa state=present password="{{ mysql_dvwa_password }}" host="{{ item }}" priv=*.*:ALL login_password="{{ mysql_root_password }}" login_user=root

  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"

- name: create new database
  mysql_db: db=dvwa state=present login_password="{{ mysql_dvwa_password }}" login_user=dvwa