---
- name: Install MariaDB packages
  ansible.builtin.apt:
    name:
      - mariadb-client
      - mariadb-server
      - python3-pymysql
    state: present

- name: Enable and start MariaDB
  ansible.builtin.service:
    enabled: true
    name: mariadb
    state: started
