---
- name: Remove anonymous MariaDB users
  ansible.mysql.mysql_user:
    config_file: ""
    host_all: true
    login_unix_socket: /run/mysqld/mysqld.sock
    name: ""
    state: absent

- name: Remove the MariaDB test database
  ansible.mysql.mysql_db:
    config_file: ""
    login_unix_socket: /run/mysqld/mysqld.sock
    name: test
    state: absent

- name: Create the DVWA database
  ansible.mysql.mysql_db:
    collation: utf8mb4_unicode_ci
    config_file: ""
    encoding: utf8mb4
    login_unix_socket: /run/mysqld/mysqld.sock
    name: "{{ dvwa_db_name }}"
    state: present

- name: Create the restricted DVWA database user
  ansible.mysql.mysql_user:
    config_file: ""
    host: localhost
    login_unix_socket: /run/mysqld/mysqld.sock
    name: "{{ dvwa_db_user }}"
    password: "{{ dvwa_db_password }}"
    priv: "{{ dvwa_db_name }}.*:ALL"
    state: present
  no_log: true
