---
- name: Deletes anonymous MySQL server user for localhost
  mysql_user:
    user: ""
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"


- name: update mysql root password for all root accounts
  mysql_user:
    user: root
    host: "{{ host }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"

- name: Removes the MySQL test database
  mysql_db:
    db: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: creating dvwa DB user
  mysql_user:
    user: "{{ dvwa_db_username }}"
    state: present
    password: "{{ mysql_dvwa_password }}"
    host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"

- name: create DVWA database
  mysql_db:
    db: dvwa
    state: present
    login_user: "{{ dvwa_db_username }}"
    login_password: "{{ mysql_dvwa_password }}"
