---
- name: Download DVWA from github via git clone
  git: 
    repo: https://github.com/ethicalhack3r/DVWA.git
    dest: /var/www/html/DVWA
    update: yes
    force: yes

- name: folder and file permissions for upload
  file: path="/var/www/html/DVWA/hackable/uploads" mode=0777 recurse=yes

- name: php ids file permissions
  file: path="/var/www/html/DVWA/external/phpids/0.6/lib/IDS/tmp" mode=0777 recurse=yes

- name: Config directory  permissions
  file: path="/var/www/html/DVWA/config" mode=0777 recurse=yes
