---
- name: Download DVWA from github via git clone of the master branch
  ansible.builtin.git:
    repo: https://github.com/digininja/DVWA.git
    dest: /var/www/html/DVWA
    clone: true
    update: true
    force: true
    version: master

- name: Folder and file permissions for upload
  ansible.builtin.file:
    path: "/var/www/html/DVWA/hackable/uploads"
    mode: 0777
    recurse: true

- name: PHP ids file permissions
  ansible.builtin.file:
    path: "/var/www/html/DVWA/external/phpids/0.6/lib/IDS/tmp"
    mode: 0777
    recurse: true

- name: Config directory permissions
  ansible.builtin.file:
    path: "/var/www/html/DVWA/config"
    mode: 0777
    recurse: true
