---

- name: Adding repo ppa:ondrej/apache2
  apt_repository:
    repo: 'ppa:ondrej/apache2'

- name: Adding repo ppa:ondrej/php
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Installing webserver(apache) & git
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: present

  vars:
    packages:
    - apache2
    - git
