---
- name: Update the APT package index
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true

- name: Install Apache and Git
  ansible.builtin.apt:
    name:
      - apache2
      - git
    state: present

- name: Enable and start Apache
  ansible.builtin.service:
    enabled: true
    name: apache2
    state: started
