---
- name: Configure PHP for DVWA labs
  ansible.builtin.template:
    dest: "/etc/php/{{ dvwa_php_version }}/apache2/conf.d/99-dvwa.ini"
    group: root
    mode: "0644"
    owner: root
    src: dvwa.ini.j2
  notify:
    - Restart Apache
