---
- name: Install PHP5.6
  apt:
    update_cache: yes
    name: "{{ packages }}"
    state: present

  vars:
    packages:
      - php5.6
      - libapache2-mod-php5.6
      - php5.6-mcrypt
      - php5.6-curl
      - php5.6-mysql
      - php5.6-gd

  notify:
    - restart apache
