---
- name: Install PHP
  ansible.builtin.apt:
    update_cache: true
    name: '{{ item }}'
    state: present
  loop:
    - php
    - libapache2-mod-php
    - php-mysqli
    - php-gd
  notify:
    - Restart apache
